### ISSUE TITLE
Installation using setup.py fails

### ISSUE THREAD

**Issue by Gnurro** [potassco/clinguin#107]
Using the 1.0.0 release, installing via the supplied setup.py script fails on a fresh conda environment.

Error message:
`error: h11 0.14.0 is installed but h11<0.13,>=0.11 is required by {'httpcore'}`

The conda environment was just created.

I'd appreciate a timely reply and resolution, as clinguin is needed for a current project for the ASP course at UP. The deadline is the 31st of March, and this issue prevents even starting to get familiar with clinguin, not to mention actual work on the project.

**Comment by Gnurro** [comment]
The same issue occurs when trying this using a blank salte base python venv.

**Comment by susuhahnml** [comment]
Hi! Can you tell which version of pip and python you are using? Also the command you used to install this. Thanks

**Comment by susuhahnml** [comment]
I just updated the dependencies, this might now help. 
I was able to install using a clean environment with pip version 22.3.1
```
pip install git+https://github.com/potassco/clinguin.git
```

**Comment by alexl4123** [comment]
Hey @Gnurro  
Does the issue still persist? If so could you maybe try to install Clinguin from the `dev` branch (if latest on `dev` doesn't work try commit with hash `9723513d571ea4fc5e8c01752de774fe4e029d22`)

**Comment by Gnurro** [comment]
> Hey @Gnurro Does the issue still persist? If so could you maybe try to install Clinguin from the `dev` branch (if latest on `dev` doesn't work try commit with hash `9723513d571ea4fc5e8c01752de774fe4e029d22`)

I don't know. I ended up using a version supplied by the course lecturer for the project.

**Comment by alexl4123** [comment]
> > Hey @Gnurro Does the issue still persist? If so could you maybe try to install Clinguin from the `dev` branch (if latest on `dev` doesn't work try commit with hash `9723513d571ea4fc5e8c01752de774fe4e029d22`)
> 
> I don't know. I ended up using a version supplied by the course lecturer for the project.

Hi @Gnurro 

thanks for your fast response. I will therefore consider this issue as closed (if it won't appear again).
