### ISSUE TITLE
Changing the background color of a button doesn't work on MacOS

### ISSUE THREAD

**Issue by TamaraAtanasoska** [potassco/clinguin#111]
Hi! I was doing a project for the ASP intro course at Uni Potsdam when I realised that I can't change the background color of a button with the options provided. After some research it seems that this is not `clinguin` related, but a Tkinter issue([link to a StackOverflow discussion about it](https://stackoverflow.com/questions/1529847/how-to-change-the-foreground-or-background-colour-of-a-tkinter-button-on-mac-os)). 
Some people use the `highlightbackground` attribute to go around the inherent problem, but it doesn't seem to consistently cover all cases and it doesn't have the same effect as a `background_color`. 

I used a label and shaped it as a button where this works great for me for the time being. I think there isn't much that can be done, maybe including this attribute `highlightbackground`, although it won't be the same. Maybe just a little warning for the MacOS users I guess if they land here with the same issue.

**Comment by TamaraAtanasoska** [comment]
> Thank you! In future development we will consider adding this attribute. And new frontends so that we don't have to deal with these tkinter issues.

Thanks, that makes very much sense! I think the label-as-a-button strategy doesn't look bad too at all.

**Comment by susuhahnml** [comment]
Great! Sorry for not being able to take care of the issues at the moment. Alex (who made the system) will be back in july and catch up with some of these issues and further development. We are very open to feedback and feature ideas.
