### ISSUE TITLE
Required dependency: zlib

### ISSUE THREAD

**Issue by rtaupe** [potassco/clinguin#116]
I'm trying to install clinguin on Windows using `python setup.py install`, but I'm getting the following error:

> setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for zlib,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n')

This also happens after I installed zlib (with GnuWin32).

**Comment by rtaupe** [comment]
Hi @alexl4123,

Thank you, but unfortunately all of these options produce the same error.
How is zlib supposed to be found? Do I need to manually set some environment variable or something similar?

**Comment by alexl4123** [comment]
Hi @rtaupe 

Thank you for your answer, and sorry for my late response.
As far as I know, zlib is somehow needed by `setuptools`, but not directly by clinguin.
Normally it is not required to specify the location of any package manually.

Could you maybe give us your:
1.) Python version: `python --version`
2.) List the pip packages of your python environment: `python -m pip list`
3.) Operating system
4.) Full Stack trace?
5.) Any other information you deem necessary

I hope I can help you then :)

All the best
Alex

**Comment by rtaupe** [comment]
Hi!

1.) Python 3.10.4

2.) 

> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> Package              Version
> -------------------- -----------
> Arpeggio             2.0.0
> attrs                22.2.0
> build                0.10.0
> CacheControl         0.12.11
> certifi              2022.12.7
> cffi                 1.15.1
> charset-normalizer   2.1.1
> cleo                 2.0.1
> clingo               5.5.2
> clingraph            1.1.0
> clinguin             0.0.1b0
> Clorm                1.4.0
> clyngor              0.4.2
> colorama             0.4.6
> copperbench          0.2
> crashtest            0.4.1
> distlib              0.3.6
> dulwich              0.21.3
> exceptiongroup       1.1.0
> filelock             3.9.0
> graphviz             0.20.1
> h11                  0.12.0
> html5lib             1.1
> httpcore             0.13.3
> idna                 3.4
> importlib-metadata   6.0.0
> iniconfig            2.0.0
> installer            0.6.0
> jaraco.classes       3.2.3
> Jinja2               3.1.2
> jsonschema           4.17.3
> keyring              23.13.1
> lockfile             0.12.2
> MarkupSafe           2.1.3
> more-itertools       9.1.0
> msgpack              1.0.4
> nbconvert            7.3.1
> nbformat             5.8.0
> nbsphinx             0.9.1
> networkx             3.1
> numpy                1.24.2
> packaging            23.0
> pandas               1.5.3
> pexpect              4.8.0
> pip                  23.0.1
> pkginfo              1.9.6
> platformdirs         2.6.2
> pluggy               1.0.0
> poetry               1.4.0
> poetry-core          1.5.1
> poetry-plugin-export 1.3.0
> popper-ilp           2.0.0
> ptyprocess           0.7.0
> pycodestyle          2.10.0
> pycparser            2.21
> pydotplus            2.0.2
> pyparsing            3.0.9
> pyPEG2               2.15.2
> pyproject_hooks      1.0.0
> pyrsistent           0.19.3
> pyswip               0.2.10
> pytest               7.2.1
> python-dateutil      2.8.2
> pytz                 2022.7.1
> pywin32-ctypes       0.2.0
> rapidfuzz            2.13.7
> regex                2022.4.24
> requests             2.28.1
> requests-toolbelt    0.10.1
> setuptools           58.1.0
> shellingham          1.5.0.post1
> six                  1.16.0
> Sphinx               6.2.1
> sphinx-rtd-theme     1.2.0
> tk                   0.1.0
> tomli                2.0.1
> tomlkit              0.11.6
> traitlets            5.9.0
> trove-classifiers    2023.2.20
> urllib3              1.26.13
> virtualenv           20.20.0
> webencodings         0.5.1
> windows-curses       2.3.1
> zipp                 3.15.0
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
> 
> [notice] A new release of pip is available: 23.0.1 -> 23.2.1
> [notice] To update, run: python.exe -m pip install --upgrade pip

3.) Windows 10.0.19044 Build 19044

4.) 
[clinguin_install.txt](https://github.com/potassco/clinguin/files/12701431/clinguin_install.txt)

Thank you and best regards,
Richard

**Comment by rtaupe** [comment]
On current master and following the current installation instructions, installation now works on my machine :)
Thanks!
