### ISSUE TITLE
addition of new element type: Scrollbar

### ISSUE THREAD

**Issue by alexpieper** [potassco/clinguin#118]
For larger Components in a UI, a scrollbar can be added in tkinter. This option would be great to have in clinguin.

In the ui.lp, this would look like the following: 

```
element(scrollbar_test, scrollbar, container).
attribute(scrollbar_test, orient, "vertical").
```

According to the docs, this is limited to a canvas object.
(https://tk-tutorial.readthedocs.io/en/latest/scrollbar/scrollbar.html)

**Comment by susuhahnml** [comment]
This is better in Angular, so I will close this issue.
