### ISSUE TITLE
Separate Height and Width

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clinguin#123]
See if there is a way to set only one of them.

**Comment by Cedricmartens** [comment]
Specifically for buttons, dropdown menus and labels.
These elements are currently in a frame and then made to fit the frame to allow for setting their size in pixels. This prevents setting only one of these values, as the frame will be ignored if either height or width is not set and the button itself set width/height based on text size.

**Comment by alexl4123** [comment]
- Also investigate for containers

**Comment by alexl4123** [comment]
- Implementation of separate height and width in general works to a certain extend (see commit 754365d), but comes at a cost of reduced performance and still doesn't work for all layout managers as would be intuitive
