### ISSUE TITLE
Error in tkinter/sudoku_single_shot example

### ISSUE THREAD

**Issue by rtaupe** [potassco/clinguin#162]
When running
`clinguin client-server --domain-files examples/tkinter/sudoku_single_shot/instance.lp examples/tkinter/sudoku_single_shot/encoding.lp --ui-files examples/tkinter/sudoku_single_shot/ui.lp --backend=ClingoBackend --frontend=TkinterFrontend`
as suggested in https://github.com/potassco/clinguin/blob/master/examples/tkinter/sudoku_single_shot/README.md,
I get the following error:

> clinguin: error: unrecognized arguments: --domain-files examples/tkinter/sudoku_single_shot/instance.lp examples/tkinter/sudoku_single_shot/encoding.lp --ui-files examples/tkinter/sudoku_single_shot/ui.lp

**Comment by susuhahnml** [comment]
Thank you for posting this. It is now fixed in the latest version #db80e26249f9fa0d53fb398b890b3ddeac4bb57e that will be released soon.
