### ISSUE TITLE
Think about Client-Server responsibilities.

### ISSUE THREAD

**Issue by alexl4123** [potassco/clinguin#56]
Currently it is the case, that the software-architecture is quite client heave, i.e. the client has a lot of responsibility.
This means, that each client defines what attributes are possible, what values of the attributes are acceptable,  parsers them and checks if they are valid. It could be more useful for the general project, if at least parts of this responsibility will be moved to the server. In any case this needs to be discussed and if changes shall be made, they should be done pretty quickly, as the refactorment cost increases with further development.

Possible options are e.g.:
1. The attributes are globally defined, i.e. are the same for every client-implementation. This would give the backend the chance to validate the attributes and only send valid ones to the client. Further this validation should then include a check, if correct element-types are provided, the values of the attributes are correct, etc.
2. Leave it as it is, i.e. each client could have different attributes, and attribute-values. Therefore the client needs to parse and error check this behavior.

**Comment by susuhahnml** [comment]
For now we can keep this in the server side.
