### ISSUE TITLE
Install requirements

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clinguin#69]
We should divide the requirements to have some extra options lone for clingraph, one for tkinter one for ipwidgets etc.

See how is done in clingraph. 
`pip install .[tex]`

**Comment by alexl4123** [comment]
There are some problems regarding the way how we import packages in clinguin, therefore more refactoring has to be done to implement these changes effectively (see e.g. the `parse_input.py` file, the `default_backend_exec_string` and `default_frontend_exec_string` which essentially prevents us from doing this with tkinter & clingraph)
